### ISSUE TITLE
Support for other file formats like epub, xps, cbz, mobi, fb2, svg

### ISSUE THREAD

**Issue by arun-mani-j** [ArtifexSoftware/mupdf.js#115]
Hii

First of all, thanks for `mupdf.js` (and that too WASM), it is super cool!

I come from `PyMuPDF` background, there we could load epub, xps, cbz, mobi, fb2, svg file formats and work with them just like PDF documents. Does `mupdf.js` also work the same way? Can one load other formats except PDF?

I tried using https://github.com/ArtifexSoftware/mupdf.js/blob/master/examples/simple-viewer/index.html and modified the `input` element to accept epub files too. But when an epub file is opened, I get this error from console:

```js
Uncaught (in promise) Error: cannot find document handler for file type: 'alice-in-wonderland.epub'
    5735545 http://0.0.0.0:8000/dist/mupdf-wasm.js:995
    runEmAsmFunction http://0.0.0.0:8000/dist/mupdf-wasm.js:4272
    _emscripten_asm_const_int http://0.0.0.0:8000/dist/mupdf-wasm.js:4275
    invoke_vi http://0.0.0.0:8000/dist/mupdf-wasm.js:5715
    libmupdf_wasm http://0.0.0.0:8000/dist/mupdf-wasm.js:705
    openDocument http://0.0.0.0:8000/dist/mupdf.js:1184
    openFile http://0.0.0.0:8000/:22
```

Perhaps, I'm missing something, and I need to modify the script used to make it support epub?

Thanks!

(Sorry if it is duplicate, I searched for epub in issues and it did not bring up anything).

**Comment by jamie-lemon** [comment]
This is related to the file size of the WASM library and to try to keep it as small as possible, due to file size concerns, see: https://github.com/ArtifexSoftware/mupdf.js/blob/master/BUILDING.md#building - _"In order to keep it as small as possible, it is built with a minimal feature set that excludes the more refined CJK fonts, PDF scripting, XPS format, and EPUB format support."_
I expect build commands could possibly be added to support these formats.

**Comment by robinwatts** [comment]
In order to support epub, we'd need to include harfbuzz into the compilation. This would be the first library to be included that uses C++, albeit in the least impactfull way possible.

I wouldn't be 100% sure that including C++ wouldn't cause problems with wasm. It might be fine, but such is the immaturity of the wasm eco-system that I wouldn't want to bet either way without trying.

**Comment by julian-smith-artifex-com** [comment]
PyMuPDF uses loads of C++ these days, and works fine on Pyodide, so things might work ok?

**Comment by arun-mani-j** [comment]
> In order to keep it as small as possible, it is built with a minimal feature set that excludes the more refined CJK fonts, PDF scripting, XPS format, and EPUB format support.

I don't know much about WASM, so just out of my curiosity, is there any disadvantage of large WASM files? (Like browser support etc.) except the potential network bandwidth?

If there is none, I could try to compile MuPDF.js with epub support (or better Artifex provides us a "full-variant", like `npm i mupdf-full` :see_no_evil:). Because I'm using MuPDF.js in my Tauri app - network bandwidth is not an issue.

> In order to support epub, we'd need to include harfbuzz into the compilation

I share the same doubt, but as someone with no experience with WASM, I will leave it to the experts :sweat_smile:.

**Comment by ccxvii** [comment]
Why we don't ship everything is mainly a matter of deployment size affecting bandwidth and startup time for loading and compiling the wasm bytecode to native code.

Changing the build scripts to enable other components such as XPS and EPUB should just work.

However, dealing with multiple build configurations and deployments in NPM is a nightmare I'd very much like to avoid.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by arun-mani-j** [comment]
I tried building MuPDF with PDF and EPUB support due to frustration of lack of decent PDF and EPUB libraries. For those interested, this was my changes to `build.sh`.

```diff
mupdf.js master 8s 
❯ git diff build.sh
diff --git a/build.sh b/build.sh
index 7a9066c..570ea24 100644
--- a/build.sh
+++ b/build.sh
@@ -3,7 +3,7 @@
 MUPDF_DIR=libmupdf
 EMSDK_DIR=/opt/emsdk
 
-MUPDF_OPTS="-Os -DTOFU -DTOFU_CJK_EXT -DFZ_ENABLE_XPS=0 -DFZ_ENABLE_SVG=0 -DFZ_ENABLE_CBZ=0 -DFZ_ENABLE_IMG=0 -DFZ_ENABLE_HTML=0 -DFZ_ENABLE_EPUB=0 -DFZ_ENABLE_JS=0 -DFZ_ENABLE_OCR_OUTPUT=0 -DFZ_ENABLE_DOCX_OUTPUT=0 -DFZ_ENABLE_ODT_OUTPUT=0 -DMEMENTO_STACKTRACE_METHOD=0"
+MUPDF_OPTS="-Os -DTOFU -DTOFU_CJK_EXT -DFZ_ENABLE_XPS=1 -DFZ_ENABLE_SVG=1 -DFZ_ENABLE_CBZ=1 -DFZ_ENABLE_IMG=1 -DFZ_ENABLE_HTML=1 -DFZ_ENABLE_EPUB=1 -DFZ_ENABLE_JS=1 -DFZ_ENABLE_OCR_OUTPUT=0 -DFZ_ENABLE_DOCX_OUTPUT=0 -DFZ_ENABLE_ODT_OUTPUT=0 -DMEMENTO_STACKTRACE_METHOD=0"
 
 export EMSDK_QUIET=1
 source $EMSDK_DIR/emsdk_env.sh
```

Just follow official `BUILD.md` and add these changes. The build process takes around ~5 minutes on my Debian Testing with 24 GB RAM.

What is surprising is, the size of output is not that drastically big 😃 .

Size of files with XPS, SVG, CBZ, IMG, HTML, EPUB, JS (don't know what JS means here) enabled:
```sh
ls -lh
total 12M
-rw-rw-r-- 1 arun-mani-j arun-mani-j  34K Apr 16 20:44 mupdf.d.ts
-rw-rw-r-- 1 arun-mani-j arun-mani-j 106K Apr 16 20:44 mupdf.js
-rw-rw-r-- 1 arun-mani-j arun-mani-j 3.6K Apr 16 20:44 mupdfjs.d.ts
-rw-rw-r-- 1 arun-mani-j arun-mani-j  37K Apr 16 20:44 mupdfjs.js
-rw-rw-r-- 1 arun-mani-j arun-mani-j 300K Apr 16 20:44 mupdf-wasm.js
-rwxrwxr-x 1 arun-mani-j arun-mani-j  11M Apr 16 20:44 mupdf-wasm.wasm*
-rw-rw-r-- 1 arun-mani-j arun-mani-j  738 Apr 16 20:44 tasks.d.ts
-rw-rw-r-- 1 arun-mani-j arun-mani-j 2.3K Apr 16 20:44 tasks.js
```

Roughly 12 MB.

For comparison, for the official library installed through `npm install mupdf`:
```sh
ls -lh node_modules/mupdf/dist/
total 11M
-rw-rw-r-- 1 arun-mani-j arun-mani-j  34K Apr 16 20:53 mupdf.d.ts
-rw-rw-r-- 1 arun-mani-j arun-mani-j 106K Apr 16 20:53 mupdf.js
-rw-rw-r-- 1 arun-mani-j arun-mani-j 3.6K Apr 16 20:53 mupdfjs.d.ts
-rw-rw-r-- 1 arun-mani-j arun-mani-j  37K Apr 16 20:53 mupdfjs.js
-rw-rw-r-- 1 arun-mani-j arun-mani-j 293K Apr 16 20:53 mupdf-wasm.js
-rwxrwxr-x 1 arun-mani-j arun-mani-j  11M Apr 16 20:53 mupdf-wasm.wasm*
-rw-rw-r-- 1 arun-mani-j arun-mani-j  738 Apr 16 20:53 tasks.d.ts
-rw-rw-r-- 1 arun-mani-j arun-mani-j 2.3K Apr 16 20:53 tasks.js
```

Roughly 11 MB.

Hopefully I'm not doing something wrong.

I loaded an EPUB file (https://www.gutenberg.org/ebooks/11) in the `examples/simple-viewer`. It worked nicely. There was this warning in logs though.
```js
warning: unknown epub version: 3.0 mupdf-wasm.js:1582:16
    put_char http://localhost:8000/dist/mupdf-wasm.js:1582
    write http://localhost:8000/dist/mupdf-wasm.js:1528
    write http://localhost:8000/dist/mupdf-wasm.js:3303
    doWritev http://localhost:8000/dist/mupdf-wasm.js:4665
    _fd_write http://localhost:8000/dist/mupdf-wasm.js:4679
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:5092973
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:5133422
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:5140386
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:5106455
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:1040507
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:1040790
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:1040850
    invoke_viii http://localhost:8000/dist/mupdf-wasm.js:5965
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:3314427
    invoke_vii http://localhost:8000/dist/mupdf-wasm.js:5943
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:3299132
    invoke_iiii http://localhost:8000/dist/mupdf-wasm.js:5954
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:3297587
    invoke_iiiiiii http://localhost:8000/dist/mupdf-wasm.js:5998
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:779991
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:780651
    invoke_iiii http://localhost:8000/dist/mupdf-wasm.js:5954
    <anonymous> http://localhost:8000/dist/mupdf-wasm.wasm:226371
    createExportWrapper http://localhost:8000/dist/mupdf-wasm.js:705
    openDocument http://localhost:8000/dist/mupdf.js:1280
    openDocumentFromBlob http://localhost:8000/examples/simple-viewer/worker.js:64
    onmessage http://localhost:8000/examples/simple-viewer/worker.js:32
```

Anyway for my basic use case of displaying EPUB, this is more than enough, thanks a lot MuPDF team!

**Comment by jamie-lemon** [comment]
Super! Thanks for the confirmation! :)
