### ISSUE TITLE
progressive streams

### ISSUE THREAD

**Issue by conor-mac-aoidh** [ArtifexSoftware/mupdf.js#118]
Hi,

I have read the progressive streams docs [here](https://mupdf.readthedocs.io/en/latest/progressive-loading.html#progressive-streams). I have implemented a `StreamHandle` based on the example [here](https://github.com/ArtifexSoftware/mupdf.js/blob/master/examples/scripts/custom-stream.js#L7-L40). This should enable streaming a file using a `ReadableStream` returned from the `fetch` API:

```typescript
class WorkerBlobStream {
    blob: Blob;
    parts: any[] = [];
    fileReader: FileReaderSync;
    totalLoaded = 0;

    constructor(private size: number) {
        this.fileReader = new FileReaderSync()
    }

    load(part: any) {
        this.parts.push(part);
        this.blob = new Blob(this.parts);
        this.totalLoaded += part.length;
        console.log(`loaded ${this.totalLoaded}/${this.size} bytes`);
    }

    fileSize() {
        return this.size;
    }

    read(memory, offset, size, position) {
        let end = position + size;
        if (end > this.totalLoaded) {
            console.error(`asked for ${end}, only ${this.totalLoaded} loaded`);
            end = this.totalLoaded;
            //throw 'FZ_ERROR_TRYLATER'
        }
        const data = this.fileReader.readAsArrayBuffer(this.blob.slice(position, end));
        memory.set(new Uint8Array(data), offset);
        return data.byteLength;
    }

    close() {
        (this.fileReader as any) = null;
        (this.blob as any) = null;
    }
}
```

This does kind of work - I am usually able to render the first few pages. But I get a lot of errors printed in the console, such as `warning: object missing 'endobj' token`, followed by blank/empty pages.

What should the `read` method return when the bytes requested are not loaded yet? The documentation suggests that a `FZ_ERROR_TRYLATER` error should be thrown. This doesn't appear to work. Also I read [here](https://github.com/ArtifexSoftware/mupdf/blob/e9ea319a17192abc22c7d73c4fffdc453ef8dae2/docs/src/changes.rst#changes-from-114-to-115) that this functionality has been removed.

Thanks

**Comment by ccxvii** [comment]
The function needs to block until you can return the requested bytes. Returning fewer bytes than requested is equivalent to reaching the end of the file, which is why you see these error messages.

The TryLater stuff requires special handling in the calling code to be able to detect the error and retry the operation later, and as you saw it's not available in the JS bindings.

**Comment by conor-mac-aoidh** [comment]
@ccxvii Thanks for the quick response. The problem with blocking is that it will prevent the worker from processing the streamed HTTP response.. so blocking here will get stuck forever. It would be nice if this method could be async.
