### ISSUE TITLE
User friendly page cropping

### ISSUE THREAD

**Issue by jamie-lemon** [ArtifexSoftware/mupdf.js#18]
Can we do something in our mupdf.js file to allow for an easy way to crop a page?

In PyMUPDF we have: https://pymupdf.readthedocs.io/en/latest/the-basics.html#cropping-a-pdf , but I can't see the equivalent in our API.

Please let's add this to the API to match the way PyMuPDF provides it.

**Comment by ccxvii** [comment]
```
var doc = mupdf.Document.openDocument(fs.readFileSync("test.pdf"), "application/pdf")
var page = doc.loadPage(0)
page.setPageBox("CropBox", [ 0, 0, 500, 500 ])
```

**Comment by jamie-lemon** [comment]
Sorry I get: `TypeError: page.setPageBox is not a function`

**Comment by jamie-lemon** [comment]
Oh wait - I'm just appreciating the other recent commits - I'll have to package up a local mupdf node package
