### ISSUE TITLE
The pdf content include "1" could not be copied correctly 

### ISSUE THREAD

**Issue by Mowmowj** [ArtifexSoftware/mupdf.js#26]
<img width="692" alt="image" src="https://github.com/ArtifexSoftware/mupdf.js/assets/24759562/afc8c6e9-013e-4bc5-a52d-5ebc7d4aec25">

pdf: 
[raw.pdf](https://github.com/ArtifexSoftware/mupdf.js/files/14431362/raw.pdf)

open the attach file in this url:
https://mupdf.com/wasm/demo/view.html?file=../../docs/mupdf_explored.pdf

**Comment by jamie-lemon** [comment]
Yes, you are correct it is an issue with bad encoding if you build for the source code here and try the `examples/simple-viewer` demo then you'll notice the problem isn't there as we introduced a fix for this issue on MuPDF some time ago ( we just hadn't updated that mupdf.com/wasm/view.html page). 
I have just updated the page so this problem should be resolved now.

Thanks for logging the issue!

**Comment by Mowmowj** [comment]
> Yes, you are correct it is an issue with bad encoding. If you build with the source code here and try the `examples/simple-viewer` demo then you'll notice the problem isn't there as we introduced a fix for this issue on MuPDF some time ago ( we just hadn't updated that mupdf.com/wasm/view.html page). I have just updated the page so this problem should be resolved now.
> 
> Thanks for logging the issue!
@jamie-lemon 
Great! It's really working for me now and I'm going to close this issue. Thank you for your efficient contribution and timely response.

BTW
@robinwatts 
Hi Robin, sorry for bothering, I found [this commit](https://github.com/ArtifexSoftware/mupdf/commit/86148eadc868ea5cc7775e750cd3c945dce04604)  which commited by you in the mupdf source code, wondering if you could give me some simple tips about it, I'm really curious to know is this commit's aim to fix this similar issue? if yes I wanna get some inspiration from it about how to fix similar issue in other pdf viewers. Thanks~
