### ISSUE TITLE
Update npm build to 0.1.4 to include typescript changes

### ISSUE THREAD

**Issue by thaoula** [ArtifexSoftware/mupdf.js#30]
Hi Team,

Just wondering when you will be updating the npm version to 0.1.4 to get the awesome Typescript changes that were made 4 days ago?

Regards,
Tarek

**Comment by jamie-lemon** [comment]
Hi Tarek, 

Thanks for your message. The NPM version will be updated as soon as the next release of MuPDF happens ( hopefully sometime within the next couple of days ). We are basically ready to go, but as MuPDF.js depends on MuPDF itself we want to base the next release on the latest version. I'll leave this issue open and ping you once we release!

All the best,
Jamie

**Comment by jamie-lemon** [comment]
@thaoula Just a heads-up - it should be available in the next few days - will be a version `0.2.0` due to the upgrade to supporting Typescript! Watch this space!

**Comment by jamie-lemon** [comment]
@thaoula Sooner than I thought - we have just published `0.2.0` to NPM! Also updated the documentation to include a _"Getting Started with Node.js"_ section too - please see: https://mupdfjs.readthedocs.io/en/latest/how-to-guide/node/index.html

**Comment by thaoula** [comment]
Hi @jamie-lemon,

Many thanks for the update and the team's hard work.

I just installed 0.2.0 but had to use the import as follows -
`import * as mupdf from 'mupdf/dist/mupdf'`

Regards,
Tarek

**Comment by ccxvii** [comment]
You've got the wrong path in the import. It should be:

import * as mupdf from **"mupdf"**

**Comment by thaoula** [comment]
Hi @ccxvii,

I know it should be like that. However, when i do attempt to import it that way ... Vscode complains mupdf is not a module. 

Regards,
Tarek

**Comment by ccxvii** [comment]
Have you configured the typescript module resolution to use "nodenext"?

**Comment by jamie-lemon** [comment]
@thaoula I am also having a problem when I try to compile the TS - it can't find the import. A plain "mjs" file can though, will investigate further ...

**Comment by ccxvii** [comment]
You also need to do one of two things to use ESM modules with typescript:

1) Change the package.json type to "module" to use ESM

-OR-

2) Change the file suffix to "mts" instead of "ts"

The easiest way to do this (without changing your configuration files) is being very explicit in the tsc command:

`tsc -m nodenext test.mts`

**Comment by ccxvii** [comment]
To summarize how to use this in a brand new project (`foo` in this example):

```
~ $ mkdir foo
~ $ cd foo
~/foo $ npm install mupdf
~/foo $ npm install typescript
~/foo $ echo '{"compilerOptions":{"module":"nodenext"}}' > tsconfig.json
~/foo $ echo 'import * as mupdf from "mupdf"; console.log(mupdf)' > test.mts
~/foo $ npx tsc
~/foo $ node test.mjs
~/foo $ code .
```

**Comment by jamie-lemon** [comment]
Also updated the page here for future reference: https://mupdfjs.readthedocs.io/en/latest/how-to-guide/node/typescript/index.html
