### ISSUE TITLE
Annotation: Supply API to get RD value from an annotation

### ISSUE THREAD

**Issue by jamie-lemon** [ArtifexSoftware/mupdf.js#32]
Required for rendering FreeTextCallout properly. Determining the textbox's location is only possible through calculating the bbox and RD. (please refer to the attached picture for clarification)

![image](https://github.com/ArtifexSoftware/mupdf.js/assets/107279992/0d746bf0-04a7-4b35-b6b5-ca895f4ce788)

**Comment by ccxvii** [comment]
The RD property is handled internally by the core library for the annotations that use it. There should be no need for accessing this explicitly from JS.

The details of editing the text box and the callout line can be handled in issue #39
