### ISSUE TITLE
Annotation: "Intended Type" API

### ISSUE THREAD

**Issue by jamie-lemon** [ArtifexSoftware/mupdf.js#38]
Supply an API for Intended Type (IT) 

These are subtypes for example for Line and Polygon..

**Comment by ccxvii** [comment]
Present in core and added to mupdf.js in commit f5b9ff4416a61dc01b1b640dc61ac7ccc61573e4.

However, many of the intent types require additional features to be actually useful.

For example it makes no sense to set FreeTextCallout intent without being able to set the callout line (issue #39).
Likewise for the various Dimension intents (issue #42).
