### ISSUE TITLE
"Error: invalid page number: 2"

### ISSUE THREAD

**Issue by Jap2-0** [ArtifexSoftware/mupdf.js#63]
I was trying to open one of my go-to pdfs for stress testing, but this seems to occur when trying to open any pdf in Firefox (nightly).

Stack trace:

```
Error: invalid page number: 2                                                    viewer.js:750:11
    2114013 https://mupdf.com/wasm/demo/lib/mupdf-wasm.js:1142
    _emscripten_asm_const_int https://mupdf.com/wasm/demo/lib/mupdf-wasm.js:3820
    invoke_vi https://mupdf.com/wasm/demo/lib/mupdf-wasm.js:6179
    createExportWrapper https://mupdf.com/wasm/demo/lib/mupdf-wasm.js:994
    loadPage https://mupdf.com/wasm/demo/lib/mupdf.js:1392
    getPageSize https://mupdf.com/wasm/demo/worker.js:78
    onmessage https://mupdf.com/wasm/demo/worker.js:39
    open_document_from_file https://mupdf.com/wasm/demo/viewer.js:750
    onchange https://mupdf.com/wasm/demo/index.html:1
```

**Comment by Jap2-0** [comment]
Nevermind, I also see this in Edge at https://mupdf.com/wasm/demo/index.html.

**Comment by Jap2-0** [comment]
Nevermind, this is dependent on the pdf I'm testing with.  (Examples coming shortly.)

**Comment by Jap2-0** [comment]
Samples where this occurs:

https://edocs-public.dot.state.mn.us/edocs_public/DMResultSet/download?docId=26427545
https://edocs-public.dot.state.mn.us/edocs_public/DMResultSet/download?docId=12276121

**Comment by Jap2-0** [comment]
[Highway 14 expansion map-12276121-v4-2.PDF](https://github.com/ArtifexSoftware/mupdf.js/files/15072432/Highway.14.expansion.map-12276121-v4-2.PDF)

**Comment by jamie-lemon** [comment]
This should now be resolved for you - please recheck, we just had to align that live demo page with what we have on the repo in `examples/simple-viewer`.

Please confirm it works and we can close this issue - thanks!

**Comment by Jap2-0** [comment]
Yep, that fixes it.

----

(Just as a side note—feel free to ignore this—if you want an absolute torture test for PDF readers to play around with, check out https://drive.google.com/file/d/1GQTR_epMR0rdkkDiW-C_3HlAgao7sgb1/view.  I won't blame you for not looking at it, both Acrobat and Firefox have difficulty rendering it.)
