### ISSUE TITLE
Page: Draw as SVG API

### ISSUE THREAD

**Issue by steren** [ArtifexSoftware/mupdf.js#64]
`Page.toPixmap()` allows exporting the page to a raster image.

I am looking for an API to export as SVG.

I see [`mutool draw`](https://mupdf.readthedocs.io/en/latest/mutool-draw.html#mutool-draw) has the ability to export as `svg`. It also seems that [another Wasm port of MuPDF has support for drawing as SVG](https://github.com/andytango/mupdf-js). So I assume MuPDF has this capability, and it only needs to be exposed as an API in the JS library.

**Comment by jamie-lemon** [comment]
@ccxvii What do you think? Is it possible to expose such an API?

**Comment by jamie-lemon** [comment]
@steren This should now be available with the latest release of mupdf.js (0.2.1) on NPM - https://www.npmjs.com/package/mupdf , please confirm!

**Comment by steren** [comment]
Thanks, I confirm it works, here is my code:

```
	function renderPage(pdf, i) {

		const page = pdf.loadPage(i)

		const buf = new mupdf.Buffer()
		const wri = new mupdf.DocumentWriter(buf, "svg", "")
		const dev = wri.beginPage(page.getBounds())
		page.run(dev, [1, 0, 0, 1, 0, 0])
		wri.endPage()
		wri.close()

		const svgString = buf.asString();

		const svg = new Blob([svgString], { type: "image/svg+xml" });
		const img = new Image();
		img.src = URL.createObjectURL(svg);
		img.onload = function () {
			document.getElementById("render").appendChild(img);
		}

	}
```

**Comment by steren** [comment]
I would recommend:

1. documenting this use case better
2. Adding helper functions to the Page object (e.g. `Page.toSVG()`)
