### ISSUE TITLE
simple-viewer search always skips results from the current page

### ISSUE THREAD

**Issue by xybei** [ArtifexSoftware/mupdf.js#78]
The search function of `simple-viewer` has some minor flaws.

When I type in the search panel and click `Next` for the first time, the search results on the current page are always skipped and the results on the next page are displayed directly.

It is expected that the search results on the current page should be displayed first, and when `Next` is clicked again, the results on the next page will be displayed.

**Comment by jamie-lemon** [comment]
@mipo1357 Can you take a look into this?

**Comment by mipo1357** [comment]
I will look into it.

**Comment by xybei** [comment]
Hi! @mipo1357 
This fix does not seem to be very friendly to Chinese characters. 
When I input and search for Chinese, I need to type several letters `"zhong"` to enter the Chinese character `"中"` (for example, it appears on the first page), but when I type the first letter `"z"` (it appears on the fifth page), the `input `event will be triggered and the search will be started, the view will jump to the fifth page. Even if I enter the complete character `"中"` later, the character `"中"` on the first page has been skipped.
