### ISSUE TITLE
Issue converting pdf to png containing a graph with mupdf-wasm but works in mutools

### ISSUE THREAD

**Issue by mfts** [ArtifexSoftware/mupdf.js#85]
I am just wondering if there's a different setting between mutools defaults and the mupdf-wasm defaults that I'm not considering. 

the mupdf-wasm conversion:
![CleanShot 2024-05-27 at 18 38 06@2x](https://github.com/ArtifexSoftware/mupdf.js/assets/4049052/297ece8c-b9d4-41b0-bfc2-33c073e1c06d)

the mutools conversion:
![CleanShot 2024-05-27 at 18 39 23@2x](https://github.com/ArtifexSoftware/mupdf.js/assets/4049052/fc3740d0-6897-4967-b7e9-6b6907d52211)

the original pdf page graph:
![CleanShot 2024-05-27 at 18 39 23@2x](https://github.com/ArtifexSoftware/mupdf.js/assets/4049052/149f3dca-c6ba-4d7f-a622-d0799a9c7707)

**Comment by jamie-lemon** [comment]
Hmmm, could you possible add the PDF you are converting and the code sample?

**Comment by ccxvii** [comment]
@mfts We're waiting for that example.

**Comment by mfts** [comment]
Sorry for the delay. I need to ask for permission to share the document publicly first. Will get back to you.
