### ISSUE TITLE
The fix for issue #78 is not complete

### ISSUE THREAD

**Issue by xybei** [ArtifexSoftware/mupdf.js#98]
The fix for issue #78 does not seem to be very friendly to Chinese characters.
When I input and search for Chinese, I need to type several letters `"zhong"` to enter the Chinese character `"中"` (for example, it appears on the first page), but when I type the first letter `"z"` (it appears on the fifth page), the `input `event will be triggered and the search will be started, the view will jump to the fifth page. Even if I enter the complete character `"中"` later, the character `"中"` on the first page has been skipped.

**Comment by jamie-lemon** [comment]
@xybei Sorry for the late reply - are you able to provide a sample document that we can test against?

**Comment by xybei** [comment]
Here is a sample file: [test.pdf](https://github.com/user-attachments/files/16777596/test.pdf)

This is a GIF I recorded to reproduce the problem. If you want to reproduce the problem, you need to use a Chinese input method (such as the Microsoft Pinyin input method in Windows).
![chrome-capture-2024-8-28-2](https://github.com/user-attachments/assets/4bba3bbf-6719-472f-886b-f84d220bfbef)

This problem is caused by changing the `onchange` event to `oninput` when fixing issue #78. We should keep using `onchange`, that is, wait until the input is completed before starting the search. I think issue #78 should be solved by optimizing the processing logic of `current_search_page`.

**Comment by jamie-lemon** [comment]
@xybei As this is a complicated UI issue I think the best solution is to **not** listen for "on input" or "on change" events on the search text field as this will always be problematic.
Please check out the branch referenced on https://github.com/ArtifexSoftware/mupdf.js/pull/111 and let me know how it works for you.

**Comment by xybei** [comment]
Thank you @jamie-lemon. Adding a "Search" button is an innovative idea, but there is a small flaw in my test.

If the target word only appears in the pages before the current page, clicking "Search" cannot trigger the display of "Prev" or "Next", and thus cannot search for the previous words.

Considering that search boxes usually use two buttons, I submitted a pull request https://github.com/ArtifexSoftware/mupdf.js/pull/112. Please see if it is acceptable?

**Comment by jamie-lemon** [comment]
Sure - I will check it out and get back to you. 👍

**Comment by xybei** [comment]
This issue has been addressed by pull request #112
